DROP TABLE IF EXISTS single_cell_expression;
CREATE TABLE IF NOT EXISTS single_cell_expression (
    GENETIC_PROFILE_ID int NOT NULL,
    SAMPLE_ID int NOT NULL,
    TISSUE varchar(255) NOT NULL,
    CELL_TYPE varchar(255) NOT NULL,
    ENTREZ_GENE_ID int NOT NULL,
    EXPRESSION_VALUE float,
    FOREIGN KEY(GENETIC_PROFILE_ID) REFERENCES genetic_profile(GENETIC_PROFILE_ID) ON DELETE CASCADE,
    FOREIGN KEY(SAMPLE_ID) REFERENCES sample(INTERNAL_ID) ON DELETE CASCADE,
    FOREIGN KEY(ENTREZ_GENE_ID) REFERENCES gene(ENTREZ_GENE_ID) ON DELETE CASCADE
);
